language: python

python:
  - "3.8"

sudo: false
dist: bionic

install:
  - pip install --quiet pylint

script:
  - python3 -m unittest -v
  - pylint *.py sbot

notifications:
  email:
    on_success: change
    on_failure: change
