language: python

python:
  - "3.8"

sudo: false
dist: bionic

install:
  - pip install --quiet pylint

script:
  - pylint *.py sbot

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.rizon.net#raylu"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
