name: 'CI'
description: 'run commands inside docker with newer py3 with newer sqlite3'

inputs:
  cmd:
    description: 'The command to run in the container'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - sh
    - '-c'
    - ${{ inputs.cmd }}
