# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: unittest
      uses: ./ # use action.yaml in this repo
      with:
        cmd: python3 -m unittest -v
    - name: ruff
      uses: ./
      with:
        cmd: ruff check --format=github .
